Eleven/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'Eleven.views.home', name='home'),
    url(r'^about$', 'Eleven.views.about', name='about'),
    url(r'^blog/', include('blog.urls')),
    url(r'^upload-pic$', 'Eleven.views.upload_pic', name='pictureupload'),
    url(r'^admin/', include(admin.site.urls)),
)

blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import *

urlpatterns = patterns(('blog.views'),
    url(r'^(?P<page>\d+)/$', 'article_list', name='articlelist'),
    url(r'^$', 'article_list', name='articlelist'),
    url(r'^article/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<id>\d+)/$', 'article_show', name='detailarticle'),
    url(r'^article/tag/(?P<id>\d+)/$', 'article_tag_filter', name='filtrarticletag'),
    url(r'^article/class/(?P<id>\d+)/$', 'article_class_filter', name='filtrarticleclass'),
    url(r'^article/archives/(?P<id>\d+)/$', 'article_archive_filter', name='filtrarticlearchive'),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^article/add/$', 'article_add', name='addarticle'),
    url(r'^article/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<id>\w+)/update/$', 'article_update', name='updatearticle'),
    url(r'^article/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<id>\w+)/del/$', 'article_del', name='delarticle'),
    url(r'^article/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<id>\d+)/commentshow/$', 'article_show_comment', name='showcomment'),
)

blog/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Tag(models.Model):
    tag_name = models.CharField(max_length=20, blank=True)
    create_time = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.tag_name

class Classification(models.Model):
    name = models.CharField(max_length=20)
    create_time = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

class Archive(models.Model):
    year = models.IntegerField(default=datetime.today().year)
    month = models.IntegerField(default=datetime.today().month)

    def __unicode__(self):
        return str(self.year) + '-' + str(self.month)

class Author(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField(blank=True)
    website = models.URLField(blank=True)

    def __unicode__(self):
        return u'%s' % (self.name)

def GetArchive():
    archives = Archive.objects.filter(year=datetime.today().year).filter(month=datetime.today().month)
    if len(archives) == 0:
        archive = Archive()
        archive.save()
        return archive
    return archives[0]

class Article(models.Model):
    caption = models.CharField(max_length=30)
    subcaption = models.CharField(max_length=50, blank=True)
    author = models.ForeignKey(Author)
    tags = models.ManyToManyField(Tag, blank=True)
    archive = models.ForeignKey(Archive, default=GetArchive)
    classification = models.ForeignKey(Classification)
    content = models.TextField()
    publish_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    click_times = models.IntegerField(default=0)

    def __unicode__(self):
        return u'%s %s %s' % (self.caption, self.author, self.publish_time)

    class Meta:
        ordering = ['-publish_time']

blog/forms.py
from django import forms

class ArticleForm(forms.Form):
    caption = forms.CharField(label='title', max_length=100)
    content = forms.CharField(widget=forms.Textarea)

class TagForm(forms.Form):
    tag_name = forms.CharField()

class ClassificationForm(forms.Form):
    classification_name = forms.CharField()

blog/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render_to_response
from blog.models import Article, Archive
from blog.models import Tag, Classification
from django.http import Http404
from django.http import HttpResponseRedirect
from django.template import RequestContext
from blog.models import Author
from blog.forms import ArticleForm
from blog.forms import TagForm, ClassificationForm
from datetime import datetime
from django.contrib.auth.decorators import login_required
import Eleven.settings as settings


def article_list(request, page='1'):
    tags = Tag.objects.all()
    classifications = Classification.objects.all()
    archives = Archive.objects.all()
    id_end = Article.objects.get_query_set().count()
    print id_end
    if page=='0':
        page = '1'
    id_end = id_end - settings.PAGE_SIZE*(int(page) - 1)
    id_beg = id_end - settings.PAGE_SIZE
    if id_beg < 0:
        id_beg = 0
    print id_beg, id_end
    archives_count_map = {x:len(x.article_set.all()) for x in archives}
    articles = Article.objects.all().filter(id__gt = id_beg).filter( id__lte= id_end)
    if len(Article.objects.all()) > 0:
        max_id = Article.objects.all()[0].id
        pages = str((max_id+settings.PAGE_SIZE-1)/settings.PAGE_SIZE)
    else:
        pages = 1
    return render_to_response("article_list.html", {"articles": articles, "tags": tags, "classifications": classifications, "archives_count_map": archives_count_map, "page": page, "pages": pages}, context_instance=RequestContext(request))

def article_show(request, year='', month='', day='', id=''):
    tags = Tag.objects.all()
    classifications = Classification.objects.all()
    archives = Archive.objects.all()
    archives_count_map = {x:len(x.article_set.all()) for x in archives}
    try:
        article = Article.objects.get(id=id)
        if [year, month, day] != str(article.publish_time).split()[0].split('-'):
            raise Article.DoesNotExist
        article.click_times += 1
        article.save()
    except Article.DoesNotExist:
        raise Http404
    return render_to_response("article_show.html", {"article": article, "tags": tags, "classifications": classifications, "archives_count_map": archives_count_map}, context_instance=RequestContext(request))

def article_tag_filter(request, id=''):
    tags = Tag.objects.all()
    tag = Tag.objects.get(id=id)
    articles = tag.article_set.all()
    classifications = Classification.objects.all()
    archives = Archive.objects.all()
    archives_count_map = {x:len(x.article_set.all()) for x in archives}
    return render_to_response("article_tag_filter.html",
        {"articles": articles, "tag": tag, "tags": tags, "classifications": classifications, "archives_count_map": archives_count_map}, context_instance=RequestContext(request))

def article_class_filter(request, id=''):
    classifications = Classification.objects.all()
    classification = Classification.objects.get(id=id)
    articles = classification.article_set.all()
    tags = Tag.objects.all()
    archives = Archive.objects.all()
    archives_count_map = {x:len(x.article_set.all()) for x in archives}
    return render_to_response("article_class_filter.html",
        {"articles": articles, "classification": classification, "classifications": classifications, "tags": tags, "archives_count_map": archives_count_map}, context_instance=RequestContext(request))

def article_archive_filter(request, id=''):
    archives = Archive.objects.all()
    archives_count_map = {x:len(x.article_set.all()) for x in archives}
    archive = Archive.objects.all().get(id=id)
    articles = archive.article_set.all()
    tags = Tag.objects.all()
    classifications = Classification.objects.all()
    return render_to_response("article_archive_filter.html",
        {"articles": articles, "archive": archive, "archives_count_map": archives_count_map, "tags": tags, "classifications": classifications}, context_instance=RequestContext(request))

@login_required
def article_add(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        tag = TagForm(request.POST)
        classification = ClassificationForm(request.POST)
        if form.is_valid() and tag.is_valid() and classification.is_valid():
            cd = form.cleaned_data
            cdtag = tag.cleaned_data
            cdclassification = classification.cleaned_data
            tagname = cdtag['tag_name']
            classification_name = cdclassification["classification_name"]
            for taglist in tagname.split():
                Tag.objects.get_or_create(tag_name=taglist.strip())
            if classification_name != "":
                 Classification.objects.get_or_create(name=classification_name.strip())
            title = cd['caption']
            author = Author.objects.get(id=1)
            content = cd['content']
            article = Article(caption=title, author=author, content=content)
            article.classification = Classification.objects.get(name=classification_name.strip())
            article.save()
            for taglist in tagname.split():
                article.tags.add(Tag.objects.get(tag_name=taglist.strip()))
                article.save()
            id = Article.objects.order_by('-publish_time')[0].id
            return HttpResponseRedirect('/blog/article/%s/%s/' % ('/'.join(str(article.publish_time).split()[0].split('-')), id))
    else:
        form = ArticleForm()
        tag = TagForm(initial={'tag_name': 'notags'})
        classification = ClassificationForm()
    return render_to_response('article_add.html',
        {}, context_instance=RequestContext(request))

@login_required
def article_update(request, year='', month='', day='', id=""):
    id = id
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        tag = TagForm(request.POST)
        if form.is_valid() and tag.is_valid():
            cd = form.cleaned_data
            cdtag = tag.cleaned_data
            tagname = cdtag['tag_name']
            tagnamelist = tagname.split()
            for taglist in tagnamelist:
                Tag.objects.get_or_create(tag_name=taglist.strip())
            title = cd['caption']
            content = cd['content']
            article = Article.objects.get(id=id)
            if article:
                article.caption = title
                article.content = content
                article.save()
                for taglist in tagnamelist:
                    article.tags.add(Tag.objects.get(tag_name=taglist.strip()))
                    article.save()
                tags = article.tags.all()
                for tagname in tags:
                    tagname = unicode(str(tagname), "utf-8")
                    if tagname not in tagnamelist:
                        notag = article.tags.get(tag_name=tagname)
                        article.tags.remove(notag)
            else:
                article = Article(caption=article.caption, content=article.content)
                article.save()
            return HttpResponseRedirect('/blog/article/%s/%s/' % ('/'.join(str(article.publish_time).split()[0].split('-')), id))
    else:
        try:
            article = Article.objects.get(id=id)
            if [year, month, day] != str(article.publish_time).split()[0].split('-'):
                raise Article.DoesNotExist
        except Exception:
            raise Http404
        tags = article.tags.all()
        if tags:
            taginit = ''
            for x in tags:
                taginit += str(x) + ' '
            tag = taginit
        else:
            tag = ''
    return render_to_response('article_add.html',
        {'article': article, 'id': id, 'tag': tag},
        context_instance=RequestContext(request))

@login_required
def article_del(request, year='', month='', day='', id=""):
    try:
        article = Article.objects.get(id=id)
        if [year, month, day] != str(article.publish_time).split()[0].split('-'):
            raise Article.DoesNotExist
    except Exception:
        raise Http404
    if article:
        article.delete()
        return HttpResponseRedirect("/blog")
    articles = Article.objects.all()
    return render_to_response("article_list.html", {"articles": articles})

def article_show_comment(request, year='', month='', day='', id=''):
    article = Article.objects.get(id=id)
    if [year, month, day] != str(article.publish_time).split()[0].split('-'):
            raise Http404
    return render_to_response('article_comments_show.html', {"article": article})

templates/blog/article_add.html
{% extends "article_base.html" %}

{% block title %} 发布文字 {% endblock %}
{% block script %}
{{ block.super }}
<script type="text/javascript">
        var writer = new stmd.HtmlRenderer();
        var reader = new stmd.DocParser();

        $(document).ready(function() {
          var parsed;
          var render = function() {
              if (parsed === undefined) {
                return;
              }
              var result = writer.renderBlock(parsed);
              $("#preview").html(result);
          };
          var parseAndRender = function () {
              parsed = reader.parse($("#id_content").val());
              render();
          };

          $("#preview-button").bind('click', parseAndRender);
          // $("#id_content").bind('keyup paste cut mouseup', parseAndRender);
          // $(".option").change(render);
        });
  </script>
{% endblock %}


{% block article %}

<form role="form" action="" method="post" xmlns="http://www.w3.org/1999/html">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_caption">Title: </label>
        {% if form.caption.errors %}
        <div class="alert alert-error">
            {{ form.caption.errors }}
        </div>
        {% endif %}
        <input type="text" class="form-control" id="id_caption" name="caption" placeholder="标题" value="{{ article.caption }}">
    </div>
    <div class="form-group">
        <label for="id_content">Content: </label>
        {% if form.content.errors %}
        <div class="alert alert-error">
            {{ form.content.errors }}
        </div>
        {% endif %}
        <textarea class="form-control" rows="5" style="height:300px" id="id_content" name="content">{{ article.content }}</textarea>
    </div>
    <div class="input-group">
        <div class="input-group-addon">tags</div>
        {% if tag.tag_name.errors %}
        <div class="alert alert-error">
            {{ tag.tag_name.errors }}
        </div>
        {% endif %}
        <input type="text" colum class="form-control" id="id_tag" name="tag_name" placeholder="Tag" value="{{ tag }}">

        <div class="input-group-addon">classification</div>
        {% if classification.classification_name.errors %}
        <div class="alert alert-error">
            {{ classification.classification_name.errors }}
        </div>
        {% endif %}
        <input type="text" colum class="form-control" id="id_classification" name="classification_name" placeholder="Classification" value="{{ article.classification }}">
    </div>
    <br/>
    <button type="submit" class="btn btn-primary">Save</button>
    <button class="btn btn-primary" data-toggle="modal" data-target="#myModal" id="preview-button">Preview</button>
     <br/>
    <!-- Modal -->
    <div class="modal fade bs-example-modal-lg" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg"  style="width:70%;">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="myModalLabel">Preview</h4>
          </div>
          <div class="modal-body">
            <div id="preview" class="tab-pane active">
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        </div>
      </div>
    </div>

</form>
{% endblock %}

templates/blog/article_archive_filter.html
{% extends "article_base.html" %}

{% block title %} tag: {{ tag }} {% endblock %}
{% block script %}
{{ block.super }}
{% endblock %}

{% block article %}
<article class='content-main'>
    <h1>归档: {{ archive }}</h1><br/>
    {% for article in articles %}
        <h4><a href="{% url 'detailarticle' year=article.publish_time|date:"Y" month=article.publish_time|date:"m" day=article.publish_time|date:"d" id=article.id %}">{{ article.caption }}</a></h4>
        <p class="text-muted">
            <i class="glyphicon glyphicon-list-alt"></i> <small>{{ article.classification }}</small>
            {% for tag in article.tags.all %}
                <i class="glyphicon glyphicon-tags"></i> <small>{{ tag }}</small>
            {% endfor %}
            <i>, {{ article.click_times }} visits</i>
        </p>
        <div class="row">
            <div class="col-md-3">
                <p class="muted"><i class="glyphicon glyphicon-time"></i><small> {{ article.publish_time|date:"Y-m-d" }}</small></p>
            </div>
            <div class="col-md-2 col-md-offset-7">
                {# <a href="{% url 'delarticle' article.id %}" title="delete"><i class="glyphicon glyphicon-trash"></i></a> #}
                {# <a href="{% url 'updatearticle' article.id %}" title="edit"><i class="glyphicon glyphicon-pencil"></i></a> #}
                <a href="{% url 'detailarticle' year=article.publish_time|date:"Y" month=article.publish_time|date:"m" day=article.publish_time|date:"d" id=article.id %}#disqus_thread" title="comment">
                <i class="ds-thread-count glyphicon glyphicon-comment" data-thread-key="{{ article.id }}"></i></a>
            </div>
        </div>
    <hr>
    {% endfor %}
</article>
{% endblock %}

templates/blog/article_base.html
{% extends "base.html" %}

{% block script %}
    <!-- 多说公共JS代码 start (一个网页只需插入一次) -->
    <script type="text/javascript">
    var duoshuoQuery = {short_name:"okhyf"};
        (function() {
            var ds = document.createElement('script');
            ds.type = 'text/javascript';ds.async = true;
            ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.unstable.js';
            ds.charset = 'UTF-8';
            (document.getElementsByTagName('head')[0]
             || document.getElementsByTagName('body')[0]).appendChild(ds);
        })();
    </script>
    <!-- 多说公共JS代码 end -->

    <!-- MarkDown -->
    <script type="text/javascript" src="{{ STATIC_URL }}js/stmd.js"></script>
{% endblock %}
{% block extra_head %}
{% endblock %}

{% block aside %}
    {# <a class="btn" href="{% url 'addarticle' %}"><i class="glyphicon glyphicon-plus"></i> add new blog</a> #}<br/>
    {% block introduce %}
        <div class="panel panel-default" style="box-shadow: 0px 0px 20px rgba(50, 50, 50, 0.4);">
          <div class="panel-heading text-center">About</div>
          <div class="panel-body" style="font-size:15px;font-family: sans-serif;">
            <img src="/static/img/about-me.jpg" alt="it's me!" class="img-thumbnail" style="float:left; width:60%; margin-right:5px;">
            <p>
                <strong style="padding:30px">贺于峰</strong><br/>
                网名:<strong>酷寒清风</strong><br/>
                E名:<strong>Ian Harris</strong><br/>
                职业:程序狗<br/>
                目前就职于厦门亿联网络技术股份有限公司杭州分公司, 做音视频引擎开发。
            </p>
            <p>
                专注IP通信，关注技术前沿，爱好研究各类编程语言与编程范式。
            </p>
          </div>
          <table class="table">
          </table>
        </div>
    {% endblock %}

    {% block tags %}
        <div class="well" style="box-shadow: 0px 0px 20px rgba(50, 50, 50, 0.4);">
            <i class="glyphicon glyphicon-tags"></i><i> 标签</i><br/>
            {% for tag in tags %}
                <span class="label label-info"><a href="{% url 'filtrarticletag' tag.id %}" style="color:white;">{{ tag }}</a></span>
            {% endfor %}
        </div>
    {% endblock %}

    {% block classifications %}
        <div class="well" style="box-shadow: 0px 0px 20px rgba(50, 50, 50, 0.4);">
            <i class="glyphicon glyphicon-list-alt"></i><i> 分类</i><br/>
            {% for classification in classifications %}
                <span class="label" style="font-size:13px;"><a href="{% url 'filtrarticleclass' classification.id %}">{{ classification }}</a></span>
            {% endfor %}
        </div>
    {% endblock %}

    {% block archives %}
        <div class="well" style="box-shadow: 0px 0px 20px rgba(50, 50, 50, 0.4);">
            <i class="glyphicon glyphicon-calendar"></i><i> 归档</i><br/>
            {% for archive, count in archives_count_map.items %}
                <span class="label"><a href="{% url 'filtrarticlearchive' archive.id %}" style="font-size:13px;">{{ archive }} ({{ count }})</a></span>
            {% endfor %}
        </div>
    {% endblock %}

    {% block links %}
        <div class="well" style="box-shadow: 0px 0px 20px rgba(50, 50, 50, 0.4);">
            <i class="glyphicon glyphicon-link"></i><i> 链接</i><br/>
        </div>
    {% endblock %}

    {%if user.is_authenticated%}
    {% block administration %}
        <div class="well" style="box-shadow: 0px 0px 20px rgba(50, 50, 50, 0.4);">
            <i class="glyphicon glyphicon-user"></i><i> 管理</i><br/>
            <ul>
              <li><a href="{% url 'home' %}admin">登陆后台</a></li>
              <li><a href="{% url 'addarticle' %}">写文章</a></li>
            </ul>
        </div>
    {% endblock %}
    {%endif%}
{% endblock %}

templates/blog/article_class_filter.html
{% extends "article_base.html" %}

{% block title %} classification: {{ classification }} {% endblock %}
{% block script %}
{{ block.super }}
{% endblock %}

{% block article %}
<article class='content-main'>
    <h1>分类: {{ classification }}</h1><br/>
    {% for article in articles %}
        <h4><a href="{% url 'detailarticle' year=article.publish_time|date:"Y" month=article.publish_time|date:"m" day=article.publish_time|date:"d" id=article.id %}">{{ article.caption }}</a></h4>
        <p class="text-muted">
            <i class="glyphicon glyphicon-list-alt"></i> <small>{{ article.classification }}</small>
            {% for tag in article.tags.all %}
                <i class="glyphicon glyphicon-tags"></i> <small>{{ tag }}</small>
            {% endfor %}
            <i>, {{ article.click_times }} visits</i>
        </p>
        <div class="row">
            <div class="col-md-3">
                <p class="muted"><i class="glyphicon glyphicon-time"></i><small> {{ article.publish_time|date:"Y-m-d" }}</small></p>
            </div>
            <div class="col-md-2 col-md-offset-7">
                {# <a href="{% url 'delarticle' article.id %}" title="delete"><i class="glyphicon glyphicon-trash"></i></a> #}
                {# <a href="{% url 'updatearticle' article.id %}" title="edit"><i class="glyphicon glyphicon-pencil"></i></a> #}
                <a href="{% url 'detailarticle' year=article.publish_time|date:"Y" month=article.publish_time|date:"m" day=article.publish_time|date:"d" id=article.id %}#disqus_thread" title="comment">
                <i class="ds-thread-count glyphicon glyphicon-comment" data-thread-key="{{ article.id }}"></i></a>
            </div>
        </div>
    <hr>
    {% endfor %}
</article>
{% endblock %}

templates/blog/article_comments_show.html
{% load comments %}
{% load gravatar %}
<article id="cmt">
    {% get_comment_count for article as comment_count %}
        <h4 class="text-muted">{{ comment_count }} Comments</h4>
        <hr class="soften">
    {% get_comment_list for article as article_com %}
    {% for comment in article_com %}
        <div class="container-fluid none-padding" style="word-wrap: break-word; word-break: normal;">
            <img class="gravatar" src="{% gravatar_url comment.user_email %}">
            <p class="text-muted"><small>{{ comment.name }}</small> <small>{{ comment.submit_date|date:"F j Y" }}</small></p>
            {{ comment.comment|safe }}
        </div>
        <hr class="soften">
    {% endfor %}
</article>

templates/blog/article_list.html
{% extends "article_base.html" %}

{% block title %} 浮生四季 {% endblock %}
{% block script %}
{{ block.super }}
    <script>
        $(document).ready(function() {
            $("#nav-home-item").addClass("active");
        })
    </script>
{% endblock %}
{% block extra_head %}
{{ block.super }}
<style>
.article_item
{
    padding-left:10px;
    border-left-style:solid;
    border-left-color:#CCCCCC;
    border-width: 10px;
    transition: border 1s;
    -moz-transition: border 1s;	/* Firefox 4 */
    -webkit-transition: border 1s;	/* Safari 和 Chrome */
    -o-transition: border 1s;	/* Opera */
}
.article_item:hover
{
    border-left-style:solid;
    border-left-color:#EA6753;
    border-width: 10px;
}
</style>
{% endblock %}

{% block article %}
<article class='content-main' style="box-shadow: 0px 0px 20px rgba(50, 50, 50, 0.2);padding: 20px 5px 0x 0;margin-top:40px;">
    {% for article in articles %}
    <div class="article_item">
        <h4 style="margin-top:-20px; padding-top:10px"><a href="{% url 'detailarticle' year=article.publish_time|date:"Y" month=article.publish_time|date:"m" day=article.publish_time|date:"d" id=article.id %}" >{{ article.caption }}</a></h4>
        <p class="text-muted">
            <i class="glyphicon glyphicon-list-alt"></i> <small>{{ article.classification }}</small>
            {% for tag in article.tags.all %}
                <i class="glyphicon glyphicon-tags"></i> <small>{{ tag }}</small>
            {% endfor %}
            <i>, {{ article.click_times }} visits</i>
        </p>
        <div class="row">
            <div class="col-md-3">
                <p class="muted"><i class="glyphicon glyphicon-time"></i><small> {{ article.publish_time|date:"Y-m-d" }}</small></p>
            </div>
            <div class="col-md-2 col-md-offset-7">
                {# <a href="{% url 'delarticle' article.id %}" title="delete"><i class="glyphicon glyphicon-trash"></i></a> #}
                {%if user.is_authenticated%}
                <a href="{% url 'updatearticle' year=article.publish_time|date:"Y" month=article.publish_time|date:"m" day=article.publish_time|date:"d" id=article.id %}" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                {%endif%}
                <a href="{% url 'detailarticle' year=article.publish_time|date:"Y" month=article.publish_time|date:"m" day=article.publish_time|date:"d" id=article.id %}#disqus_thread" >
                <i class="ds-thread-count glyphicon glyphicon-comment" data-thread-key="{{ article.id }}"></i></a>
            </div>
        </div>
    <hr style="border-style:solid;border-color:#CCCCCC;border-width: 2px;">
    </div>
    {% endfor %}
</article>

{% block pagination %}
<ul class="pager">
  {% ifequal page '1' %}
    <li class="previous disabled"><span>&larr; Older</span></li>
  {% else %}
    <li class="previous"><a href="{% url 'articlelist' page|add:-1 %}">&larr; Older</a></li>
  {% endifequal  %}
  {% ifequal page pages %}
    <li class="next disabled"><span>Newer &rarr;</span></li>
  {% else %}
    <li class="next"><a href="{% url 'articlelist' page|add:1 %}">Newer &rarr;</a></li>
  {% endifequal %}
</ul>
{% endblock %}

{% endblock %}

templates/blog/article_tag_filter.html
{% extends "article_base.html" %}

{% block title %} tag: {{ tag }} {% endblock %}
{% block script %}
{{ block.super }}
{% endblock %}

{% block article %}
<article class='content-main'>
    <h1>标签: {{ tag }}</h1><br/>
    {% for article in articles %}
        <h4><a href="{% url 'detailarticle' year=article.publish_time|date:"Y" month=article.publish_time|date:"m" day=article.publish_time|date:"d" id=article.id %}">{{ article.caption }}</a></h4>
        <p class="text-muted">
            <i class="glyphicon glyphicon-list-alt"></i> <small>{{ article.classification }}</small>
            {% for tag in article.tags.all %}
                <i class="glyphicon glyphicon-tags"></i> <small>{{ tag }}</small>
            {% endfor %}
            <i>, {{ article.click_times }} visits</i>
        </p>
        <div class="row">
            <div class="col-md-3">
                <p class="muted"><i class="glyphicon glyphicon-time"></i><small> {{ article.publish_time|date:"Y-m-d" }}</small></p>
            </div>
            <div class="col-md-2 col-md-offset-7">
                {# <a href="{% url 'delarticle' article.id %}" title="delete"><i class="glyphicon glyphicon-trash"></i></a> #}
                {# <a href="{% url 'updatearticle' article.id %}" title="edit"><i class="glyphicon glyphicon-pencil"></i></a> #}
                <a href="{% url 'detailarticle' year=article.publish_time|date:"Y" month=article.publish_time|date:"m" day=article.publish_time|date:"d" id=article.id %}#disqus_thread" title="comment">
                <i class="ds-thread-count glyphicon glyphicon-comment" data-thread-key="{{ article.id }}"></i></a>
            </div>
        </div>
    <hr>
    {% endfor %}
</article>
{% endblock %}